pluginManagement {
	repositories {
		mavenLocal()
		mavenCentral()
		google()
		gradlePluginPortal()
	}
}
dependencyResolutionManagement {
	repositories {
		mavenLocal()
		mavenCentral()
		google()
		maven {
			url 'https://maven.oom-wg.dev'
			content {
				includeGroupAndSubgroups 'ren.shiror'
				includeGroupAndSubgroups 'sbs.fvvlang'
			}
		}
		gradlePluginPortal()
	}
}

rootProject.name = 'ShiroSU-FYL'

include ':fytxt:plugin'
include ':fytxt:bom'
include ':fytxt:runtime:core', ':fytxt:runtime:compose', ':fytxt:runtime:systxt'