plugins {
    id 'org.jetbrains.kotlin.jvm'
    id 'java-gradle-plugin'
    id 'maven-publish'
}

group = 'dev.oom-wg.purejoy.mlang'
version = 'main'

sourceSets.main.java.srcDirs = ['src/main/kotlin', '../deps/fvv/kotlin']

dependencies {
    compileOnly gradleApi()
    compileOnly localGroovy()

    //noinspection GradleDynamicVersion
    compileOnly 'com.android.tools.build:gradle:+'
}

gradlePlugin {
    plugins {
        MLang {
            id = 'dev.oom-wg.purejoy.mlang'
            implementationClass = 'dev.oom_wg.purejoy.mlang.MLangPlugin'
            displayName = "PureJoy MultiLang Gradle Plugin"
            description = "Android Multi Language Framework"
        }
    }
}

publishing {
    repositories {
        mavenLocal()
    }
}