import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}

kotlin.compilerOptions.jvmTarget = JvmTarget.JVM_24

android {
    namespace 'dev.oom_wg.wm.wmlang.base'
    compileSdk 36

    defaultConfig {
        minSdk 16

        consumerProguardFiles "consumer-rules.pro"
    }
    sourceSets.main.java.srcDirs += 'src/main/kotlin'
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_24
        targetCompatibility JavaVersion.VERSION_24
    }
}

dependencies {}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'dev.oom-wg.wm.wmlang'
                artifactId = 'base'
                version = 'main'

                pom {
                    name.set("WMLang")
                    description.set("Android Multi Language Framework")
                    url.set("https://github.com/OOM-WG/WMLang")

                    licenses {
                        license {
                            name.set("F2DLPRL")
                            url.set("https://license.fileto.download/LICENSE.txt")
                        }
                    }

                    developers {
                        developer {
                            id.set("oom-wg")
                            name.set("OOM. WG.")
                            email.set("oom@200ok.work")
                            url.set("https://oom-wg.dev")
                        }
                    }

                    organization {
                        name.set("OOM. WG.")
                        url.set("https://oom-wg.dev")
                    }

                    scm {
                        connection.set("scm:git:https://github.com/OOM-WG/WMLang.git")
                        developerConnection.set("scm:git:https://github.com/OOM-WG/WMLang.git")
                        url.set("https://github.com/OOM-WG/WMLang.git")
                    }
                }
            }
        }
        repositories {
            mavenLocal()
        }
    }
}